* Setting Server
** Upgrade paket mongodb
   Jika menggunakan Ubuntu 13.04, versi default bawaan dari paket mongodb 
   2.2.x, sementara fitur full text search baru disertakan pada versi
   2.4.x. Untuk itu, silakan upgrade (install) mengikuti tutorial berikut:

   http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/

   Sunting berkas /etc/mongodb.conf, tambahkan baris berikut:

   #+BEGIN_SRC sh
   setParameter=textSearchEnabled=true
   #+END_SRC

   Kemudian, /restart/ mongodb Anda:

   #+BEGIN_SRC sh
     sudo service mongodb restart
   #+END_SRC

* Testing
** Database Operation
   #+BEGIN_SRC sh
   > use mydatabase
   > db.table.ensureIndex({nickname: 'text'})
   > db.table.insert({'nickname': 'kholid'})
   > db.table.runCommand('text', {search: 'kholid'})
   #+END_SRC
  
   Pertama kita buat database dengan nama mydatabase, kemudian kita membuat 
   table (collection) dengan nama 'table', kemudian kita buat field dengan 
   nama 'nickname', dan kita tetapkan bahwa jenis data yang akan kita
   kita masukkan nantinya adalah 'text'.

   Langkah selanjutnya, kita memasukkan baris data pertama kita, yakni
   'kholid', kemudian kita uji apakah fitur full text search sudah berjalan
   dengan baik dengan menjalankan perintah ke-4 di atas.
   
   Untuk melakukan pencarian di Python, gunakan syntax berikut:
   #+BEGIN_SRC sh     >>> import pymongo
     >>> c = pymongo.Connection()
     >>> db = c['images']
     >>> db.command('text', 'image', search="keyword")   
   #+END_SRC

   Dimana image disini adalah nama table.
* Tips
** Import Big Data
   Untuk melakukan import database fulltext, biar tidak /error/, buat dulu
   swap di hosting Anda, dengan cara:

  #+BEGIN_SRC sh
    
    # create new partition
    dd if=/dev/zero of=/swapfile bs=1M count=1024
    # set as swap
    mkswap /swapfile
    # activate the swap once
    swapon /swapfile
    # run every machine reboot
    /swapfile swap swap defaults 0 0 # add into /etc/fstab
    
  #+END_SRC

   Setelah itu buat /database/ terlebih dahulu, kemudian jalankan 
   =ensureIndex= melalui mongo console, baru lakukan =mongoimport=.
** Import
   Untuk melakukan import jalankan perintah berikut:
   #+BEGIN_SRC sh
     
     mongoimport --db terms --collection term --file terms.json
     
   #+END_SRC
** Export
   Untuk melakukan export jalankan perintah berikut:
   #+BEGIN_SRC sh
     
     mongoexport --db terms --collection term --out terms.json
     
   #+END_SRC
** Dump
   Dump berguna untuk mem-backup semua database yang ada di os sekaligus
   #+BEGIN_SRC sh
   
      mongodump .
      
   #+END_SRC
   Tanda =.= berarti =disini=, artinya kita buat dulu folder misal mongbckup untuk menampung semua database
   yang ada.
** Restore
   Restore ini berguna untuk mengembalikan data backup ke sistem.
   #+BEGIN_SRC sh
   
      mongorestore mongbckup/
      
   #+END_SRC
   Perintah di atas berarti mengembalikan semua database yang ada di direktori =mongbckup= ke dalam sistem.
   Jika diperlukan untuk me-restore ulang dengan cara menimpa, jalankan perintah berikut:
   #+BEGIN_SRC sh
   
      mongorestore --drop mongbckup/
      
   #+END_SRC
   
** Note
Semua perintah ini dijalankan pada mongo versi 2.2.x, 2.4.x dan 2.6.x. Saat tulisan ini diperbarui sudah muncul
mongodb versi 3, dan saya mengalami beberapa kendala. So please read again the docs!
